services:
  nest-demo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/src
    env_file:
      - .env.development
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: PM4BE-pablomos87
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-networks

volumes:
  postgres-data:

networks:
  app-networks: